function REC()
  let fname = expand('%:t:r') . ".rec"
  let lineCount = line('$')
  call system('touch ' . fname)
  call system('chmod u+x ' . fname)
  call system('echo ' . lineCount . '~$(($(date +%s%N)/1000000))' . ' >> ' . fname)
  execute 'silent! w >> ' . fname
endfunction

