function REC()
  let fname = expand('%:p') . ".rec"
  let lineCount = line('$')
  call system('touch ' . fname)
  call system('chmod u+x ' . fname)
  call system('echo ' . lineCount . '~$(($(date +%s%N)/1000000))' . ' >> ' . fname)
  execute 'silent! w >> ' . fname
endfunction

let record=0

autocmd InsertLeave *
\ if record|
\   call REC()|
\ endif

autocmd TextChanged *
\ if record|
\   call REC()|
\ endif
